CREATE DATABASE HotelManagementProject_DB

USE HotelManagementProject_DB

DROP DATABASE HotelManagementProject_DB

CREATE TABLE LOGINS(
_USERNAME VARCHAR(20) PRIMARY KEY,
_PASSWORD VARCHAR(20) NOT NULL,
_TYPE VARCHAR(30) CHECK (_TYPE IN('CUSTOMER','EMPLOYEE' ))
)

CREATE TABLE CUSTOMER (
_USERNAME VARCHAR(20) FOREIGN KEY REFERENCES LOGINS(_USERNAME)  ON DELETE CASCADE PRIMARY KEY,
_NAME VARCHAR(20) NOT NULL,
_CONTACT VARCHAR(20) NOT NULL,
_EMAIL VARCHAR(20),
_CTYPE VARCHAR(20) CHECK (_CTYPE IN('PLATINUM','SILVER','GOLD')),
)

CREATE TABLE STAFF(
_USERNAME VARCHAR(20) FOREIGN KEY REFERENCES LOGINS(_USERNAME)  ON DELETE CASCADE PRIMARY KEY,
_NAME VARCHAR(20) NOT NULL,
_CONTACT VARCHAR(20) NOT NULL,
_DESIGNATION VARCHAR(20) NOT NULL
);

--DROP TABLE ATTENDANCE
CREATE TABLE ATTENDANCE
(
    _USERNAME VARCHAR(20) FOREIGN KEY REFERENCES STAFF(_USERNAME)  ON DELETE CASCADE PRIMARY KEY,
	_DATE DATE NOT NULL,
	_CHECKIN BIT CHECK (_CHECKIN IN(1,0)),
	
);

--DROP TABLE ROOM
CREATE TABLE ROOM
(
	_ROOMID INT PRIMARY KEY,
	_ROOMTYPE CHAR(10) CHECK (_ROOMTYPE = 'Single' OR _ROOMTYPE = 'Double' OR _ROOMTYPE = 'Family'),
	_PRICEPERNIGHT INT NOT NULL,
);

CREATE TABLE ROOM_BOOKINGS
(
	_ROOMID INT FOREIGN KEY REFERENCES ROOM(_ROOMID) ON DELETE CASCADE,
	_CUSTOMERID VARCHAR(20) FOREIGN KEY REFERENCES CUSTOMER(_USERNAME) ON DELETE CASCADE,
	_TIMESLOT TIME NOT NULL,
	_DATESLOT DATE NOT NULL,
	PRIMARY KEY(_ROOMID,_CUSTOMERID)
);

--DROP TABLE GYM_BOOKING
CREATE TABLE GYM_BOOKING
(
	_TIMESLOT TIME NOT NULL,
	_CUSTOMERID VARCHAR(20) FOREIGN KEY REFERENCES CUSTOMER(_USERNAME) ON DELETE CASCADE,
	_ROOMBOOKING BIT CHECK(_ROOMBOOKING = 1 OR _ROOMBOOKING = 0)
);

--DROP TABLE DAYCARE_BOOKING

CREATE TABLE DAYCARE_BOOKING
(
	_CUSTOMERID VARCHAR(20) FOREIGN KEY REFERENCES LOGINS(_USERNAME) ON DELETE CASCADE,
	_DAYCARETIME TIME NOT NULL,
	
);
--DROP TABLE POOLS
CREATE TABLE POOLS(
 _POOLTYPE VARCHAR(20) CHECK(_POOLTYPE = 'Public' OR _POOLTYPE = 'Private') PRIMARY KEY,
 _PRICE INT NOT NULL
)
--DROP TABLE POOL_BOOKING
CREATE TABLE POOL_BOOKING
(
	_POOLTYPE VARCHAR(20) FOREIGN KEY REFERENCES POOLS(_POOLTYPE) ON DELETE CASCADE,
   _CUSTOMERID VARCHAR(20) FOREIGN KEY REFERENCES CUSTOMER(_USERNAME) ON DELETE CASCADE,

);

--DROP TABLE BILLPAYMENTGENERATOR

--CREATE TABLE BILLPAYMENTGENERATOR
--(
--	CustomerID INT FOREIGN KEY REFERENCES SYSTEM_SIGNUP,
--	ServiceID INT,
--	TotalBill INT
--);


--DROP TABLE HOTELSERVICES
CREATE TABLE HOTELSERVICES
(
  _SERVICENAME VARCHAR (20) PRIMARY KEY,
  _AVAILABILITY BIT NOT NULL,
  _PRICE INT  NULL

);

CREATE TABLE SERVICES_USAGE(
	_CUSTOMERID VARCHAR(20) FOREIGN KEY REFERENCES LOGINS(_USERNAME) ON DELETE CASCADE PRIMARY KEY,
	_SERVICENAME VARCHAR(20) FOREIGN KEY REFERENCES HOTELSERVICES(_SERVICENAME) ON DELETE CASCADE,
)
--DROP TABLE FEEDBACK

CREATE TABLE FEEDBACK
(
    _CUSTOMERID VARCHAR(20) FOREIGN KEY REFERENCES CUSTOMER(_USERNAME) ON DELETE CASCADE PRIMARY KEY,
	Rating INT CHECK (Rating >= '1' OR Rating <= '5') NOT NULL,
	Comment VARCHAR(50) NULL
);
